title: CheeseWeasel.Day
description: Celebrate Cheese Weasel Day every April 3rd!
show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine
head_image_url: /assets/images/CheeseWeaselDayTempHeaderImage.png
