title: CheeseWeasel.Day
description: ðŸ§€ Celebrate every April 3rd by giving your IT person some delicious cheese! ðŸ§€
show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine
head_image_url: /assets/images/CheeseWeaselDayTempHeaderImage.png
